<div class="boxform">
	<div class="container">
		<form class="form formtopo form-inline" method="POST" action="">
			<div class="form-group col-xs-12 col-sm-3">
				<input id="dat_first_name" class="form-control" name="dat_first_name" placeholder="First name" required="required">
			</div>
			<div class="form-group col-xs-12 col-sm-3">
				<input id="dat_last_name" class="form-control" name="dat_last_name" placeholder="Last name" required="required">
			</div>
			<div class="form-group col-xs-12 col-sm-3">
				<input id="dat_participation" class="form-control percent" name="dat_participation" placeholder="Participation" required="required">
			</div>
			<div class="form-group col-xs-12 col-sm-3">
				<button class="bt1 col-xs-12 col-sm-3" ><img src="./imagens/loading.gif" class="loading"> Send</button>
			</div>
		</form>
	</div>
</div>

<h2>DATA</h2>
<h3>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h3>

<div id="conteudo">
</div>

<!-- AJAX e JS index -->
<script src="./application/views/scripts/index/index.js"></script>